version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: app-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    ports:
      - "3306:3306"                       # 로컬에서 DB툴로 붙을 때 필요. 안 쓰면 지워도 됨
    volumes:
      - db_data:/var/lib/mysql            # DB 데이터 영속화
      - ./mysql/conf.d:/etc/mysql/conf.d  # (선택) my.cnf 조각
      - ./mysql/init:/docker-entrypoint-initdb.d  # (선택) 최초 초기화 SQL
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 15

  api:
    build: .
    container_name: vchat-api
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: ["node", "dist/main.js"]

  # 개발용(핫리로드) 옵션 — 필요 시 주석 해제해서 사용
  # dev:
  #   image: node:20-alpine
  #   working_dir: /app
  #   command: sh -c "npm ci && npm run dev"
  #   volumes:
  #     - .:/app
  #   env_file: .env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     db:
  #       condition: service_healthy

volumes:
  db_data:
